name: Build and Publish to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    # Forces GitHub to use the updated Node.js backend to clear the warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        # Upgraded from v5 to v6
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # REMEMBER TO KEEP YOUR ACTUAL USERNAME HERE
          tags: ghcr.io/neetbirb/steamybirb:latest
